name: issue-workflow
on:
  issues:
    # issue가 open 될 때 트리거가 되서 github action 실행
    types: [opend]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action
