name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    step:
      - name: echo
        run: echo "job1 done"
  job2:
    runs-on: ubuntu-latest
    needs: [job1] # job1이 성공한 이후에 실행
    step:
      - name: echo
        run: echo "job2 done"
  job3:
    runs-on: ubuntu-latest
    step:
      - name: echo
        run: | # exit 1 == github action이 강제 실패됨
          echo "job3 failed"
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3] # job3이 강제 실패 되므로 job4는 실행되지 않을 것
    step:
      - name: echo
        run: echo "job4 done"
